# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev-test2',
                'doc_host': 'https://Pankajkumar-Bankar.github.io',
                'git_url': 'https://github.com/Pankajkumar-Bankar/nbdev-test2',
                'lib_path': 'nbdev_test2'},
  'syms': {'nbdev_test2.core': {'nbdev_test2.core.foo': ('core.html#foo', 'nbdev_test2/core.py')}}}
